<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tarima extends Model
{
    //


    protected $table = 'tarimas';
    protected $primaryKey = 'id';

    public $timestamps = false;


    public function save(array $options = []): bool
    {

        if ($this->unidad_medida == 'UN') {
            $this->ubicacion = '4140754842000208';
        } else {
            $this->ubicacion = '4140754842000031';
        }
        return parent::save($options); // TODO: Change the autogenerated stub
    }


}
